server:
  port: 20002
eureka:
  instance:
    hostname: eureka-server2
  client:
    # 表示是否注册自身到eureka服务器
    # register-with-eureka: false
    # 是否从eureka上获取注册信息
    # fetch-registry: false
    service-url:
      defaultZone: http://eureka-server1:20001/eureka/