server:
  port: 1114
#properties  本地配置文件
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared  #配置本地配置文件目录
  application:
    name: config-server
  profiles:
    active: native #设置本地启动方式，而不是通过git